# Generated by Django 5.1.6 on 2025-03-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movie_image_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('show_time', 'row', 'number')},
        ),
    ]
